
CREATE TABLE EMP (
	EMP_NO VARCHAR2(30) NOT NULL,
	EMP_NAME VARCHAR2(80) NOT NULL,
	SALARY NUMBER NULL,
	HIRE_DATE DATE NULL
);

-- 확인하기
DESC EMP;

-- 테이블 삭제하기
DROP TABLE TABLE_NAME;

-- 기본키 생성
-- 방법1 : 테이블 생성시 PK 컬럼에 NOT NULL 대신 적어주기
CREATE TABLE EMP (
	EMP_NO VARCHAR2(30) PRIMARY KEY,
	EMP_NAME VARCHAR2(80) NOT NULL,
	SALARY NUMBER NULL,
	HIRE_DATE DATE NULL );

-- 방법2 : 
